name: mp3_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  file_picker: ^8.0.6
  firebase_auth: ^5.1.2
  firebase_storage: ^12.1.1
  flutter:
    sdk: flutter
  just_audio: ^0.9.39

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
