// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYnpSqHphxvXUT2jpZJx_PssRF8eRO7fo',
    appId: '1:801105802943:web:cbd7b5098beb3a612a780a',
    messagingSenderId: '801105802943',
    projectId: 'musicproj123',
    authDomain: 'musicproj123.firebaseapp.com',
    storageBucket: 'musicproj123.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx4wFL6wVNVXCPoDOCCdXDp7h3AngA3-Q',
    appId: '1:801105802943:android:48548d4bde507aa22a780a',
    messagingSenderId: '801105802943',
    projectId: 'musicproj123',
    storageBucket: 'musicproj123.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqYNV3I_xtsjKOcvU7HNGWSkLXMxGzuI4',
    appId: '1:801105802943:ios:37770b32b67e39cf2a780a',
    messagingSenderId: '801105802943',
    projectId: 'musicproj123',
    storageBucket: 'musicproj123.appspot.com',
    iosBundleId: 'com.example.mp3App',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqYNV3I_xtsjKOcvU7HNGWSkLXMxGzuI4',
    appId: '1:801105802943:ios:37770b32b67e39cf2a780a',
    messagingSenderId: '801105802943',
    projectId: 'musicproj123',
    storageBucket: 'musicproj123.appspot.com',
    iosBundleId: 'com.example.mp3App',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYnpSqHphxvXUT2jpZJx_PssRF8eRO7fo',
    appId: '1:801105802943:web:167962a27e408a1c2a780a',
    messagingSenderId: '801105802943',
    projectId: 'musicproj123',
    authDomain: 'musicproj123.firebaseapp.com',
    storageBucket: 'musicproj123.appspot.com',
  );
}
